apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app-container
        image: REPLACE_IMAGE_TAG # Placeholder for Jenkins to replace
        ports:
        - containerPort: 8080 
