apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
spec:
  selector:
    app: jenkins-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
